### ISSUE TITLE
a question about tutorial step

### ISSUE THREAD

**Issue by xukunwu** [HaominLyu/SSM#1]
perl ClusterProByLTRBlastFull.pl Fananassa.genome.fa.out.LAI.LTR.ava.out.closest SSM.ctl
The command is not correct. According parameter location(order), corrected command should perl ClusterProByLTRBlastFull.pl SSM.ctl Fananassa.genome.fa.out.LAI.LTR.ava.out.closest?

**Comment by HaominLyu** [comment]
You are right. I have revised it. Thank you.

**Comment by xukunwu** [comment]
By the way, could you give the example file about "LTR_blast_results.out"? Thank you. My assignment is always killed without error information.

**Comment by xukunwu** [comment]
this is my SSM.ctl file:
 #Input any pairs of identity intervals
UpLimit:        100,98,95,92,89,85,95,100
DownLimit:      98,95,92,89,85,80,90,96
#List all chromosome name for matrix constructions
Chromosome:     Chr01,Chr02,Chr03,Chr04,Chr05,Chr06,Chr07,Chr08,Chr09,Chr10,Chr11,Chr12,Chr13,Chr14,Chr15,Chr16,Chr17,Chr18,Chr19,Chr20,Chr21,Chr22,Chr23,Chr24,Chr25,Chr26,Chr27,Chr28,Chr29,Chr30,Chr31,Chr32,Chr33,Chr34,Chr35,Chr36

this is my primary LTR_blast file(part):
Chr05_1654-1813:.       Chr05_1654-1813:        100.000 160     0       0       1       160     1       160     1.07e-78        296
Chr05_1654-1813:.       Chr35_64035236-64035457:        90.244  164     9       6       1       160     161     1       5.17e-52        207
Chr05_1654-1813:.       Chr35_50809386-50809607:        90.244  164     9       6       1       160     62      222     5.17e-52        207
Chr05_1654-1813:.       Chr35_50809386-50809607:        96.203  79      1       2       28      105     1       78      4.14e-28        128
Chr05_1654-1813:.       Chr14_20971-21192:      90.303  165     7       8       1       160     62      222     5.17e-52        207
Chr05_1654-1813:.       Chr14_20971-21192:      83.824  136     7       7       28      160     1       124     3.23e-24        115
Chr05_1654-1813:.       Chr14_16536-16757:      90.303  165     7       9       1       160     62      222     5.17e-52        207
Chr05_1654-1813:.       Chr14_16536-16757:      96.203  79      1       2       28      105     1       78      4.14e-28        128
Chr05_1654-1813:.       Chr14_8681-8902:        90.244  164     9       6       1       160     62      222     5.17e-52        207
Chr05_1654-1813:.       Chr14_8681-8902:        92.208  77      5       1       30      105     2       78      5.40e-22        108
Chr05_1654-1813:.       Chr35_64035050-64035271:        90.566  159     8       7       6       160     156     1       6.69e-51        204
Chr05_1654-1813:.       Chr35_64035050-64035271:        94.937  79      2       2       28      105     222     145     1.93e-26        122
Chr05_1654-1813:.       Chr21_96757745-96757966:        90.566  159     8       6       6       160     156     1       6.69e-51        204
Chr05_1654-1813:.       Chr21_96757745-96757966:        84.559  136     6       8       28      160     222     99      6.93e-26        121
Chr05_1654-1813:.       Chr21_96725930-96726151:        90.625  160     6       7       6       160     156     1       6.69e-51        204
Chr05_1654-1813:.       Chr26_30842-31061:      90.506  158     9       5       6       160     66      220     6.69e-51        204
Chr05_1654-1813:.       Chr26_30842-31061:      93.590  78      3       2       29      105     1       77      3.23e-24        115
Chr05_1654-1813:.       Chr17_162140-162361:    89.634  164     10      6       1       160     62      222     2.41e-50        202
Chr05_1654-1813:.       Chr17_162140-162361:    87.500  136     2       8       28      160     1       124     1.48e-32        143
Chr05_1654-1813:.       Chr07_91995-92215:      89.634  164     9       7       1       160     62      221     2.41e-50        202
Chr05_1654-1813:.       Chr07_91995-92215:      92.405  79      4       2       28      105     1       78      4.17e-23        111
Chr05_1654-1813:.       Chr07_73791-74012:      89.634  164     10      6       1       160     62      222     2.41e-50        202
Chr05_1654-1813:.       Chr07_73791-74012:      93.671  79      3       2       28      105     1       78      8.97e-25        117
Chr05_1654-1813:.       Chr08_115131328-115131550:      89.634  164     10      6       1       160     161     1       2.41e-50        202
Chr05_1654-1813:.       Chr08_26062-27825:      89.634  164     10      6       1       160     1373    1533    2.41e-50        202
...

this is my command lines:
perl ClosestLTRMatch.pl LTR_blast_results.out > LTR_blast_results.out.closest &

perl ClusterProByLTRBlastFull.pl SSM.ctl LTR_blast_results.out.closest

**Comment by HaominLyu** [comment]
Is this the output file from LTR_retriever pipeline? LTR_retriever would name LTR elements like "**Chr05:1654..1813**". And this should be typical format of blastn.

**Comment by xukunwu** [comment]
yeah, above blast results are from blastn.

**Comment by HaominLyu** [comment]
The output tabular format of blastn is just the one for SSM.

**Comment by xukunwu** [comment]
thank you, I will have a try.
